name: GitHub Activity

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        default: tuunit
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Update GitHub Activity Readme
        uses: jamesgeorge007/github-activity-readme@master
        with:
          GH_USERNAME: ${{ inputs.name }}
          MAX_LINES: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
