name: GitHub Activity

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Update GitHub Activity Readme
        uses: jamesgeorge007/github-activity-readme@v0.4.4
        with:
          GH_USERNAME: tuunit
          MAX_LINES: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
